"use client";
import {useEffect,useRef,useState} from "react";
import {Check,Cloud,Copy,ExternalLink,Heart,Link2,MessageCircle,Mic,MicOff,Pause,Play,RotateCcw,Send,Settings2,Smile,Sparkles,Users,Video,VideoOff,Volume2} from "lucide-react";
const platforms=[{name:"Netflix",mark:"N",url:"https://www.netflix.com/browse",tone:"netflix"},{name:"Prime Video",mark:"prime",url:"https://www.primevideo.com/",tone:"prime"},{name:"ZEE5",mark:"Z5",url:"https://www.zee5.com/",tone:"zee5"},{name:"YouTube",mark:"▶",url:"https://www.youtube.com/",tone:"youtube"}];
const pad=(n:number)=>String(n).padStart(2,"0");const clock=(s:number)=>`${pad(Math.floor(s/3600))}:${pad(Math.floor((s%3600)/60))}:${pad(s%60)}`;
export default function Home(){
 const room="SKY-ABHI";const [copied,setCopied]=useState(false),[mic,setMic]=useState(true),[camera,setCamera]=useState(false),[playing,setPlaying]=useState(false);const [seconds,setSeconds]=useState(0),[countdown,setCountdown]=useState<number|null>(null),[message,setMessage]=useState("");
 const [messages,setMessages]=useState([{who:"Abhi",text:"I’m ready ☁️",time:"8:42 PM",mine:false},{who:"You",text:"Opening Netflix now",time:"8:42 PM",mine:true}]);const videoRef=useRef<HTMLVideoElement>(null),streamRef=useRef<MediaStream|null>(null);
 useEffect(()=>{if(!playing)return;const id=setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(id)},[playing]);useEffect(()=>{if(countdown===null)return;if(countdown===0){setPlaying(true);const t=setTimeout(()=>setCountdown(null),900);return()=>clearTimeout(t)}const t=setTimeout(()=>setCountdown(n=>n===null?null:n-1),1000);return()=>clearTimeout(t)},[countdown]);useEffect(()=>()=>streamRef.current?.getTracks().forEach(t=>t.stop()),[]);
 const copy=async()=>{await navigator.clipboard?.writeText(`${location.origin}?room=${room}`);setCopied(true);setTimeout(()=>setCopied(false),1500)};const toggleCamera=async()=>{if(camera){streamRef.current?.getTracks().forEach(t=>t.stop());if(videoRef.current)videoRef.current.srcObject=null;setCamera(false);return}try{const s=await navigator.mediaDevices.getUserMedia({video:true,audio:false});streamRef.current=s;if(videoRef.current)videoRef.current.srcObject=s;setCamera(true)}catch{setCamera(false)}};const send=()=>{if(!message.trim())return;setMessages(v=>[...v,{who:"You",text:message.trim(),time:new Date().toLocaleTimeString([],{hour:"numeric",minute:"2-digit"}),mine:true}]);setMessage("")};
 return <main className="shell"><header className="nav"><div className="logo"><span className="logo-mark"><Cloud/><Sparkles/></span>Sky <i>&</i> Clouds</div><div className="room"><span/>Private room <b>{room}</b></div><div className="nav-actions"><button className="settings"><Settings2/>Settings</button><button className="invite" onClick={copy}>{copied?<Check/>:<Link2/>}{copied?"Copied":"Invite Abhi"}</button></div></header>
 <section className="layout"><div className="main"><section className="watch-card"><div className="card-head"><div><small>● WATCH SESSION</small><h1>Tonight’s movie</h1></div><div className="together"><span>S</span><span>A</span><b>2 together</b></div></div><div className="screen"><div className="screen-content"><span><Cloud/></span><h2>Open your movie, then sync here</h2><p>Choose the same title on both devices. Use the countdown and shared timestamp to stay together.</p></div>{countdown!==null&&<div className="countdown"><b>{countdown===0?"PLAY":countdown}</b><small>{countdown===0?"Together now":"Get ready"}</small></div>}<div className="screen-meta"><span>● Waiting for movie</span><span>HD</span></div></div><div className="sync"><button onClick={()=>setSeconds(0)}><RotateCcw/></button><button className="play" onClick={()=>setPlaying(v=>!v)}>{playing?<Pause fill="currentColor"/>:<Play fill="currentColor"/>}</button><div className="timeline"><div><b>{clock(seconds)}</b><span>Shared timestamp</span><b>--:--:--</b></div><i><em style={{width:`${Math.min(seconds/72,100)}%`}}/></i></div><button><Volume2/></button><button className="ready" onClick={()=>{setPlaying(false);setCountdown(3)}}><Users/>3 · 2 · 1</button></div></section>
 <section className="platforms"><div className="section-head"><div><small>STREAMING SERVICES</small><h2>Choose where you’re watching</h2></div><p>Opens officially in a new tab or app.</p></div><div className="platform-grid">{platforms.map(p=><a className={`platform ${p.tone}`} href={p.url} target="_blank" rel="noreferrer" key={p.name}><span>{p.mark}</span><div><b>{p.name}</b><small>Open {p.name}</small></div><ExternalLink/></a>)}</div><div className="note"><Heart fill="currentColor"/>Sky & Clouds never handles your OTT password or video. Sign in only on the official app.</div></section></div>
 <aside><section className="call"><div className="panel-head"><span>● Together now</span><button>•••</button></div><div className="call-grid"><div className="person partner"><span className="avatar">A</span><div><b>Abhi</b><small>● Connected</small></div></div><div className="person self"><video ref={videoRef} autoPlay muted playsInline/><span className={`avatar ${camera?"hide":""}`}>S</span><div><b>You</b><small>{camera?"Camera on":"Camera off"}</small></div></div></div><div className="call-controls"><button onClick={()=>setMic(v=>!v)} className={!mic?"off":""}>{mic?<Mic/>:<MicOff/>}</button><button onClick={toggleCamera} className={!camera?"off":""}>{camera?<Video/>:<VideoOff/>}</button><button className="heart"><Heart fill="currentColor"/></button></div><p className="call-note">Your camera preview works here. Abhi’s live video needs the real-time room upgrade.</p></section>
 <section className="chat"><div className="chat-head"><span><MessageCircle/>Movie chat</span><b>2 online</b></div><div className="messages">{messages.map((m,i)=><div className={`message ${m.mine?"mine":""}`} key={i}>{!m.mine&&<span>A</span>}<div><small>{m.who} · {m.time}</small><p>{m.text}</p></div></div>)}</div><div className="reactions">{["❤️","😂","😮","🥹","☁️"].map(x=><button key={x}>{x}</button>)}</div><div className="composer"><button><Smile/></button><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Message Abhi…"/><button className="send" onClick={send}><Send/></button></div></section></aside></section><footer><span><Cloud/>Sky & Clouds</span><span>Made for Senthil & Abhi · Private movie nights</span><button onClick={copy}><Copy/>Copy room link</button></footer></main>}
